server:
  port: 8080
spring:
  application:
    name: security-web

logging:
  level:
    root: info
  file: ${spring.application.name}.log

management:
  security:
    enabled: false

atom:
  log:
    key: account