server:
  port: 8080
spring:
  application:
    name: security-web

logging:
  level:
    root: info
  file: ${spring.application.name}.log

management:
  security:
    enabled: false

info:
  account:
    login:
      url: http://localhost:8080/to-login

atom:
  log:
    key: account
  login:
    url: http://localhost:8080/to-login
